name: WeiBo_SuperTopics
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 14,22 * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: Pip install requests
      run: |
        pip3 install requests      
         
    - name: CheckIn
      run: |
        user='${{ secrets.COOKIE }}'
        alls='${{ secrets.S }}'
        
        
        user_list=()
        s_list=()
        IFS="#"
        for u in ${user[*]}
        do
        user_list[${#user_list[*]}]=${u}
        done
        for s in ${alls[*]}
        do
        s_list[${#s_list[*]}]=${s}
        done
        user_num=${#user_list[*]}
        echo "共有 $user_num 个账号，即将开始签到"
        for ((i=0;i<$user_num;i++))
        do
        python3 check.py <<EOF
        ${user_list[$i]}
        ${s_list[$i]}
        ${{secrets.PICK}}
        ${{secrets.SCKEY}}
        EOF
        done
        
